// Code generated by gowrap. DO NOT EDIT.
// template: ../../templates/log_template.go.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package log

import (
	"context"
	"os"

	"github.com/NoGambiNoBugs/go-observability-examples/internal/entity"
	"github.com/NoGambiNoBugs/go-observability-examples/internal/port"
	"github.com/rs/zerolog"
)

// CustomerUsecaseWithLog implements port.CustomerUsecase that is instrumented with zerolog logger
type CustomerUsecaseWithLog struct {
	base port.CustomerUsecase
}

// Create implements port.CustomerUsecase
func (d CustomerUsecaseWithLog) Create(ctx context.Context, customer entity.Customer) (err error) {

	nl := zerolog.Ctx(ctx)

	logger := nl.With().Fields(map[string]interface{}{
		"ctx":      ctx,
		"customer": customer}).Logger()

	defer func() {
		if err != nil {
			logger.Error().Fields(map[string]interface{}{
				"err": err}).Err(err).Str("decorator", "CustomerUsecaseWithLog").Str("method", "Create").Msg("Error detected")
		} else {
			logger.Debug().Fields(map[string]interface{}{
				"err": err}).Str("decorator", "CustomerUsecaseWithLog").Str("method", "Create").Msg("Finish")
		}
	}()
	return d.base.Create(ctx, customer)
}

// NewCustomerUsecaseWithLog instruments an implementation of the port.CustomerUsecase with simple logging
func NewCustomerUsecaseWithLog(base port.CustomerUsecase) port.CustomerUsecase {
	decorateAll := os.Getenv("DECORATE_ALL")
	decorateLog := os.Getenv("DECORATE_LOG")
	if !((decorateAll == "true" || decorateAll == "1") || (decorateLog == "true" || decorateLog == "1")) {
		return base
	}

	return CustomerUsecaseWithLog{
		base: base,
	}
}
