// Code generated by gowrap. DO NOT EDIT.
// template: ../../templates/red_histogram_template.go.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package red

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/NoGambiNoBugs/go-observability-examples/internal/entity"
	"github.com/NoGambiNoBugs/go-observability-examples/internal/port"
	"github.com/prometheus/client_golang/prometheus"
)

var CustomerUsecaseWithREDHistogramVec *prometheus.HistogramVec

// CustomerUsecaseWithREDHistogram implements port.CustomerUsecase interface with all methods wrapped with RED Histogram metric
type CustomerUsecaseWithREDHistogram struct {
	metricName string
	base       port.CustomerUsecase
}

// MetricName returns the metric name generated for port.CustomerUsecase
func (d CustomerUsecaseWithREDHistogram) MetricName() string {
	return d.metricName
}

// Create implements port.CustomerUsecase
func (d CustomerUsecaseWithREDHistogram) Create(ctx context.Context, customer entity.Customer) (err error) {
	since := time.Now()
	defer func() {
		status := "ok"
		if err != nil {
			status = "error"
		}

		labels := prometheus.Labels{
			"status": status,
			"method": "Create",
		}

		observer, err := CustomerUsecaseWithREDHistogramVec.GetMetricWith(labels)
		if err != nil {
			fmt.Printf("MetricName %s: Error to get metric with labels %v\n", d.metricName, labels)
		}

		observer.Observe(float64(time.Since(since).Milliseconds()))
	}()
	return d.base.Create(ctx, customer)
}

// NewCustomerUsecaseWithREDHistogram returns an instance of the port.CustomerUsecase decorated with red histogram metric
func NewCustomerUsecaseWithREDHistogram(
	base port.CustomerUsecase,
	subsystem string,
	constLabels prometheus.Labels,
) (decorator port.CustomerUsecase, err error) {
	decorateAll := os.Getenv("DECORATE_ALL")
	decorateRED := os.Getenv("DECORATE_RED")
	if !((decorateAll == "true" || decorateAll == "1") || (decorateRED == "true" || decorateRED == "1")) {
		return base, nil
	}

	mNamespace := strings.ToLower(strings.TrimSpace("example"))
	mSubsystem := strings.ToLower(strings.TrimSpace(subsystem))
	mName := strings.ToLower(strings.TrimSpace("customer_usecase_red"))

	metricConfig := prometheus.HistogramOpts{
		Namespace:   mNamespace,
		Subsystem:   mSubsystem,
		Name:        mName,
		Help:        "CustomerUsecase RED histogram (rate, errors and duration).",
		ConstLabels: constLabels,
		Buckets:     prometheus.ExponentialBuckets(100, 2, 5),
	}

	if CustomerUsecaseWithREDHistogramVec == nil {
		CustomerUsecaseWithREDHistogramVec = prometheus.NewHistogramVec(metricConfig, []string{"status", "method"})
	}

	decorator = CustomerUsecaseWithREDHistogram{
		metricName: prometheus.BuildFQName(mNamespace, mName, mSubsystem),
		base:       base,
	}

	return
}
